Pass ARG for MAVEN_NASHORN to Dockerfile

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -52,19 +52,20 @@ before_script:
 
 script:
 
-  - docker run 
-    -v "$HOME/.m2":/root/.m2 
-    -v "$HOME/.sonar/cache":/root/.sonar/cache
-    -e "SONARQUBE_SCANNER_PARAMS=${SONARQUBE_SCANNER_PARAMS}"
-    -e "SONAR_TOKEN=${SONAR_TOKEN}"
-    --network docker_jsql-network 
-    jsql:latest 
-    ./model/src/test/resources/vnc/execute-on-vnc.sh 
-    mvn clean verify sonar:sonar
-  - |
-    export DOCKER_RUN=$?
-    echo "docker run exit code: ${DOCKER_RUN}"
-    if [ ${DOCKER_RUN} -ne 0 ]; then exit 1; fi
+  # - docker run 
+  #   -v "$HOME/.m2":/root/.m2 
+  #   -v "$HOME/.sonar/cache":/root/.sonar/cache
+  #   -e "SONARQUBE_SCANNER_PARAMS=${SONARQUBE_SCANNER_PARAMS}"
+  #   -e "SONAR_TOKEN=${SONAR_TOKEN}"
+  #   --network docker_jsql-network 
+  #   jsql:latest 
+  #   ./model/src/test/resources/vnc/execute-on-vnc.sh 
+  #   mvn clean verify sonar:sonar
+  # - |
+  #   export DOCKER_RUN=$?
+  #   echo "docker run exit code: ${DOCKER_RUN}"
+  #   if [ ${DOCKER_RUN} -ne 0 ]; then exit 1; fi
+  - ./model/src/test/resources/docker/script/run.sh
   - ./model/src/test/resources/docker/script/verify.sh
   
 # after_success:
